source 'https://rubygems.org'

gem 'capybara', '~> 2.6', '>= 2.6.2'
gem "selenium-webdriver"
gem "sauce-connect"
gem 'cucumber'
gem 'rspec'
gem 'sinatra'
gem 'rest-client'
gem 'json', '~> 1.8', '>= 1.8.3'
gem 'rake', '~> 10.5'
gem 'byebug', '~> 8.2', '>= 8.2.2'
gem 'parallel'
gem 'capybara-screenshot'
gem 'multipart-post', '~> 2.0'
gem 'os', '~> 0.9.6'
gem 'mongo', '~> 2.2'
gem 'parallel_tests'
gem 'regex'